<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WebSocketNFCeService.Domain\WebSocketNFCeService.Domain.csproj" />
    <ProjectReference Include="..\WebSocketNFCeService.Infra\WebSocketNFCeService.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="QuestPDF" Version="2026.5.0" />
    <PackageReference Include="Zeus.Net.NFe.NFCe" Version="2026.5.20.1650" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Schemas\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
